name: 'generate_embeddings'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  verify:
    uses: ./.github/workflows/quality.yml
  generate:
    needs: verify
    if: github.ref == 'refs/heads/main'
    runs-on: intra-public-ci
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: supabase/embeddings-generator@11ad9d1643c95eedeab869935794fdefd0a9768d
        with:
          supabase-url: ${{ secrets.SUPABASE_URL }}
          supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          openai-key: ${{ secrets.OPENAI_DOC_EMBEDDINGS_KEY }}
          docs-root-path: 'docs'
